[package]
name = "day11"
version = "0.1.0"
authors = ["Ian J Sikes <ianjsikes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.2.1"
termion = "1.5.5"
